import React, { useState, useContext } from "react";
import {
    View,
    Image,
    TouchableOpacity,
    ScrollView,
    Text,
    useWindowDimensions,
} from "react-native";

import styles from "./style";

import { User } from "../../contexts/User";

export default function ModalCheckin({ navigation, route }) {
    const {
        localName,
        localAddress,
        listProducts,
    } = route.params;

    const window = useWindowDimensions();

    const { setTermsCheckIn } = useContext(User);

    const [terms, setTerms] = useState(false);

    return (
        <View style={styles.modalView}>
            <TouchableOpacity
                style={styles.closeModal}
                onPress={() => navigation.navigate("InternalHotel", {
                    localName,
                    localAddress,
                    listProducts,
                })}
            >
                <Image source={require("../../assets/icons/close-yellow.png")} />
            </TouchableOpacity>

            <ScrollView
                style={{ height: window.height - 200, width: "100%" }}
            >
                <View>
                    <Text maxFontSizeMultiplier={1.2} style={styles.titleTerms}>1. INTRODUÇÃO AOS TERMOS E CONDIÇÕES DE USO</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.subtitleTerms}>1.1. QUEM SOMOS E QUAL É O NOSSO OBJETIVO</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>
                        Seja bem-vindo(a) à plataforma Zoox Pass. Somos a ZOOX SOLUÇÕES EM TECNOLOGIA LTDA (também referida como “nós”, “nossos”, “Zoox” ou “empresa”), pessoa jurídica de direito privado, inscrita no CNPJ sob o nº08.668.202/0001-18, com sede na Rua Equador, nº 43, Bloco 3, Sala 319, Santo Cristo, na Cidade do Rio de Janeiro - Estado do Rio de Janeiro e fornecemos serviço de pré check-in online em redes hoteleiras e diversas funcionalidades atribuídas ao check-in (também referido como “Pass”, “produto” ou “serviço”).
                        Neste documento, queremos apresentar a você (também “usuário”, “usuário final” ou “titular de dados”) nossos Termos e Condições de Uso do produto (“termos”, “condições”, “contrato” ou “regulamentos”) pois, ao aderir a estes termos no momento de cadastro na plataforma e contratar o serviço do Zoox Pass, você concorda expressamente e se declara ciente quanto às informações e condições aqui descritas.
                        A Zoox fornece uma plataforma online que oferece serviço de pré check-in em hotéis e redes conveniadas. No entanto, é importante esclarecermos a você que a Zoox não oferece serviços de acomodação, nem gerencia, realiza, aluga ou explora, por qualquer meio, nenhuma atividade própria de hotelaria. A Zoox atua apenas como intermediária entre o cliente e o estabelecimento, transferindo os dados de cadastro do hóspede no processo de pré check-in – com foco no preenchimento da Ficha Nacional de Registro de Hóspedes (FNRH) – ao estabelecimento, enviando e-mail de confirmação do preenchimento do pré check-in (e-mail de boas-vindas) com a identidade visual do Hotel para o usuário e agregando facilidades e conveniências para sua experiência.
                        É importante deixar claro que, quando você se cadastra e aceita nossos termos,  você passa a fazer parte do ecossistema da Zoox. Isso significa que as  informações contidas em nossa base de dados poderão ser utilizadas por você  em outros  dos nossos  produtos e serviços. Nesse  sentido, a Zoox  realiza uma
                        compilação e mapeamento de informações sobre  você, conforme este contrato, visando oferecer a você novos benefícios, facilidades e  conveniências cada vez mais aprimoradas de acordo com as suas preferências  e customizadas com base em suas experiências.
                    </Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.subtitleTerms}>1.2 CONTRATO LEGAL</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>
                        Ressaltamos o quanto é importante que você leia e compreenda estes termos  pois, para usufruir dos serviços de pré check-in, você precisa aceitá-los, sendo  certo que seu aceite e consentimento, conforme o caso, o(a) submete integralmente aos termos e condições de uso aqui descritos. A manifestação de consentimento a que nos  referimos deverá ser dada eletronicamente a partir da seleção da opção “LI E  ACEITO OS TERMOS DE USO”.
                        Além destes termos, disponibilizamos a você nossa Política de Privacidade que,  embora não faça parte deste regulamento, segue em documento separado e  recomendamos que você leia atentamente para entender melhor como tratamos  e cuidamos dos seus dados, como você pode gerenciar suas preferências de privacidade, solicitar correção, anonimização, acesso e exclusão de suas  informações, dentre outras possibilidades, antes de utilizar nosso produto.
                        Caso não concorde com nossos termos e condições de uso e política de  privacidade (em separado) e/ou não queira nos fornecer suas informações  pessoais, sugerimos que se abstenha em utilizar nosso produto.
                        O produto Zoox Pass será disponibilizado a você tendo como fator  condicionante ao uso apenas o cadastro, o fornecimento de suas informações  pessoais, e a autorização de compartilhamento dos seus dados com terceiros para viabilizar a intermediação de check-in online, bem como a utilização de outros produtos da Zoox por você.
                        A inexistência de contraprestação pecuniária, quanto à disponibilização do serviço prestado não se confunde e nem se relaciona a quaisquer cobranças feitas a você pelo hotel ou rede conveniada, em decorrência da contratação de hospedagem e demais obrigações contraídas. Ou seja, a utilização da plataforma não resulta em uma obrigação de pagamento a você, mas isso não importa dizer, em hipótese alguma, que haverá quaisquer descontos ou desobrigações contratuais relativas à sua reserva de hospedagem devido ao uso da nossa plataforma.
                        O presente regulamento estabelece diretrizes e critérios para o uso seguro e  apropriado da plataforma Zoox Pass e tem o objetivo reger o relacionamento  jurídico (contratação) do usuário em relação à plataforma da Zoox, descrevendo  obrigações, responsabilidades, aspectos específicos, legislações aplicáveis, direito de propriedade intelectual e as condições gerais de uso da plataforma,
                        visando coibir a utilização indevida de nosso produto e serviços.
                    </Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.titleTerms}>2. DESCRIÇÃO DO PRODUTO</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>
                        O principal objetivo do serviço de pré check-in oferecido pela Zoox via Zoox Pass é facilitar o processo de check-in, pagamentos ao hotel ou outro conveniado, e check-out relativos e oriundos da reserva de acomodação feita por você.
                        O Zoox Pass possibilita a você (a depender das funcionalidade disponíveis,  contratadas pelo próprio estabelecimento):
                    </Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>a. Fornecer uma fotografia para o sistema de reconhecimento facial viabilizar o  uso das funcionalidades de smart check-in e check-out;</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>b. Realizar o check-in dias antes de sua chegada na unidade física hoteleira;</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>c. Cadastrar PIN para sua autenticação no sistema;</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>d. Preencher os dados da FNRH (Ficha Nacional de Registro de Hóspedes);</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>e. Realizar a escolha do quarto e gravação da chave;</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>f. Solicitar upgrade de quarto ou geração de nova chave;</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>g. Solicitar serviços de quarto e serviços do hotel;</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>h. Ter acesso a informações da unidade hoteleira;</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>i. Realizar o escaneamento e envio de cópia dos documentos pessoais necessários ao hotel;</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>j. Conferir os detalhes da fatura;</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>k. Adicionar itens extras;</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>l. Adicionar cartão de crédito ou débito para pagamento.</Text>

                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>O processo de utilização compreende as seguintes etapas:</Text>

                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>a. Escolha do idioma (Português, Espanhol ou Inglês) Nesta etapa, você deverá escolher o idioma a ser utilizado durante sua interação  com o Zoox Pass.</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>b. Busca de reserva na rede hoteleira. Neste momento, você buscará sua(s) reserva(s) informando o número de CPF (Cadastro de Pessoa Física), ou número do passaporte, ou ainda informando o  número da reserva, e-mail vinculado à reserva, ou nome, sobrenome, data de  check-in e data de check-out no hotel. Como alternativa, você poderá se  autenticar utilizando a técnica de Reconhecimento Facial. Ou seja, você poderá  tirar uma foto de seu rosto, validando sua identidade no sistema e, dessa forma,  gerando acesso às suas informações e reservas. O sistema de reconhecimento facial é provido pela Amazon Web Services (AWS), plataforma mundialmente  conhecida pelo alto padrão de segurança aplicada aos dados, e é 100% opcional – ou seja, somente será utilizado com a sua autorização e mediante sua vontade.  O sistema ainda apresenta a possibilidade de trabalhar (quando a funcionalidade for contratada pelo hotel) com a coleta de mais de uma imagem, com ângulos/movimentos diferentes, para sua segurança, de modo a checar que, de  fato, é você mesmo e não uma outra pessoa que esteja usando sua imagem de forma não autorizada.</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>c. Pagamento da acomodação (OPCIONAl). Você poderá cadastrar os dados do seu cartão de crédito ou débito em uma  carteira virtual administrada pela Mundipagg, e efetuar o pagamento das suas  despesas oriundas da acomodação de forma mais prática e facilitada. Veja mais  detalhes na seção de Transações Financeiras.</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>d. Preenchimento da Ficha Nacional de Registro de Hóspedes (FNRH). Serão solicitadas as informações necessárias para composição da FNRH. Vale  destacar que muitas delas já virão preenchidas caso você já tenha utilizado o  Zoox Pass em outra ocasião e houver consentido a integrar o nosso  ecossistema. Segundo o Decreto nº 7.381, de 2 de dezembro de 2010, que  regulamenta a Lei do Turismo nº 11.771/2008, a movimentação diária de  hóspedes deve ser declarada através da Ficha Nacional de Registro de  Hóspedes, sendo obrigação do estabelecimento manter uma cópia desta  arquivada em formato eletrônico.</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>e. Assinatura (obrigatória ou opcional, a depender do hotel). Nesta etapa, você poderá assinar eletronicamente o seu nome para concluir o  processo.</Text>

                    <Text maxFontSizeMultiplier={1.2} style={styles.titleTerms}>3. CANCELAMENTO, REAGENDAMENTO OU NÃO  COMPARECIMENTO A RESERVA</Text>

                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>A Zoox, como intermediadora da sua relação direta com o hotel ou rede  conveniada, não responde pelo seu reagendamento, cancelamento ou não  comparecimento ao hotel, conforme a reserva de acomodação solicitada. Quaisquer solicitações, reclamações, sugestões ou informações relativas à sua reserva e acomodação devem ser dirigidas ao hotel ou rede conveniada por você  escolhida.</Text>

                    <Text maxFontSizeMultiplier={1.2} style={styles.titleTerms}>4. TRANSAÇÕES FINANCEIRAS</Text>

                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>Nossa plataforma disponibiliza a você a possibilidade de realizar o pagamento  de suas despesas oriundas da reserva de acomodação na rede hoteleira, através  de uma carteira virtual. Essa funcionalidade ajuda você a realizar a gestão financeira de sua  acomodação no hotel ou rede conveniada, poupando tempo em filas de espera,  por exemplo, de modo que, ao inserir as informações do seu cartão de crédito  ou débito, seja efetuada a transação financeira de forma rápida e prática. Ao se cadastrar, você deverá salvar seu cartão na carteira (“wallet”) virtual para  poder utilizá-lo na sequência. Se desejar, poderá, após o uso, removê-lo da  wallet a qualquer tempo. Visando oferecer a máxima segurança, nem a Zoox nem o hotel ou rede  conveniada terão acesso ou armazenarão os seus dados de seus cartões de  crédito. A Zoox apenas atuará como uma intermediadora da transação a ser feita em favor do hotel e o processamento do pagamento será feito integralmente pela Mundipagg, que consiste em uma plataforma digital de integração de  pagamentos pela internet de propriedade da Stone. Esclarecemos que a Mundipagg é uma empresa segura, homologada e que  segue os preceitos de Segurança da Informação exigidos pelo Banco Central e  pelas melhores práticas internacionais (PCI - Security Standards Council)  exigidas para transações.</Text>

                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>Na dinâmica de pagamento, há 6 (seis) fluxos de pagamento previstos:</Text>

                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>1. Pré-Pagamento - na Central de Reservas, conforme descrito aqui;</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>2. Registro de Garantia – no processo de pré check-in no mesmo fluxo onde  o hóspede vai preencher os dados da FNRH e escanear os documentos;</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>3. Cobranças de Pagamentos Avulsos – utilizadas em casos específicos  pelo Hotel para abater parte do saldo devedor do hóspede em uma  estadia de longa duração (“long stay”);</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>4. Cobrança de NO SHOW – quando o hóspede não comparece sem avisar  (pode ser cobrado sobre o pré pagamento, sobre o registro de garantia ou  cobrança direta);</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>5. Cobrança de Check-out – processo iniciado pelo hóspede, dentro do  Guest Control para pagamento de suas despesas realizadas durante a  hospedagem (no processo de check-out), e</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>6. Cobranças Pós Check-out – para o caso de cobranças referentes a  consumo não informado de frigobar, danos causados ao quarto ou outros  pontos identificados pela Governança na vistoria da unidade. Essa  cobrança pode ser utilizada pelo hotel ou não. Portanto, nestes 6 fluxos a dinâmica pode acontecer basicamente de 4 maneiras: </Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>a. Dinâmica 1: Da forma como foi descrito para o caso do fluxo 1 (pré pagamento na central de reserva), através do recebimento de um link para  acesso à plataforma e pagamento (fluxos 1, 3 e parte do 4, por exemplo);</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>b. Dinâmica 2: Pagamento ocorre dentro do fluxo da plataforma do Zoox Pass (Fluxo 2), como é o caso do Registro de Garantia no processo de pré  check-in;</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>c. Dinâmica 3: O processo de pagamento é iniciado pelo hóspede dentro  do Guest Control, (Fluxo 5) como é o caso do check-out, e</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>d. Dinâmica 4: O processo de cobrança é automático, baseado em um Pré Pagamento ou Registro de Garantia oferecido pelo Hóspede (parte do  Fluxo 4 e Fluxo 6).</Text>

                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>A dinâmica de pagamento se dará da seguinte forma – você, ao acessar a central  de reservas do hotel, receberá um link por e-mail para realizar o cadastro do seu  cartão e efetuar o pré-pagamento da sua reserva. Em seguida, você será  direcionado(a) a realizar um cadastro pessoal e receberá uma numeração, um código de verificação para autenticação da transação. O pagamento da reserva  será realizado e o hotel ou rede conveniada receberá a confirmação do pagamento. Depois, você será convidado(a) a complementar seu cadastro de modo a  fornecer as informações necessárias para a FNRH (Ficha Nacional de Registro  de Hóspedes) em nome da rede hoteleira.</Text>

                    <Text maxFontSizeMultiplier={1.2} style={styles.titleTerms}>5. RESPONSABILIDADES DA ZOOX</Text>

                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>A Zoox é responsável por exibir as funcionalidades do produto de forma clara e prestar os serviços de maneira completa, precisa e suficiente, de modo que você possa compreender as operações realizadas e proteger os dados coletados pela  Zoox segundo a legislação e as melhores práticas do mercado.</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>A Zoox envidará seus melhores esforços para manter a disponibilidade de suas  funcionalidades. Mas, pode ser que, eventualmente, ocorra alguma  indisponibilidade temporária devido à manutenção necessária ou mesmo gerada  por motivo de caso fortuito ou força maior (ocasiões que fogem ao controle da  Zoox), como desastres naturais, falhas nos sistemas de comunicação e acesso  à Internet ou atividades de terceiro que fogem da esfera de controle, vigilância e  responsabilidade da Zoox, não sendo a Zoox responsável por qualquer desses  eventos, nem mesmo pela indisponibilidade gerada por eles.</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>Se isso ocorrer, a Zoox fará o que estiver ao seu alcance para restabelecer o  acesso ao produto e serviços da Zoox o mais breve possível, dentro de suas  limitações técnicas e de terceiros dos quais a Zoox depende para ficar  disponível.</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>A Zoox não é responsável por:</Text>

                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>a. Serviços prestados por terceiros disponíveis ou referenciados pela Zoox, sendo que você deverá verificar e estar ciente de contratos, termos e  condições dos terceiros para que você os contrate e use os respectivos serviços, uma vez que a é Zoox apenas uma “ponte” (intermediadora)  entre você e esses terceiros;</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>b. Falhas de acesso à Zoox decorrentes de circunstâncias relacionadas à  indisponibilidade da Internet em geral, quedas de energia, mau  funcionamento digital ou físico de qualquer rede de telecomunicações,  interrupções ou suspensões de conexão e falhas nos softwares (programas de computador) e/ou hardwares (dispositivos) utilizados por  você;</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>c. Quaisquer problemas ou funcionamentos indevidos que ocorrerem nos  seus dispositivos e equipamentos;</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>d. Erros de sistemas que alterem dados ou informações da Zoox;</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>e. Qualquer dano direto ou indireto ocasionado por eventos de terceiros,  como ataques de hackers, falhas no sistema, no servidor ou na conexão  à Internet, inclusive por ações de softwares (programas de computador)  maliciosos, como vírus, cavalos de Tróia e outros que possam, de algum  modo, danificar o seu equipamento ou a sua conexão, bem como a transferência de dados, arquivos, imagens, textos, áudios ou vídeos  contidos no seu equipamento, e</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>f. Informações contidas nos cadastros feitos por meio da Zoox, sendo certo que a veracidade, atualização e exatidão dos dados e informações que  você cadastrar na Zoox são de sua inteira responsabilidade, sendo que  você poderá responder civil e penalmente pela incorreção dos dados.</Text>

                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>A Zoox pode, de acordo com seus objetivos de negócio, modificar, suspender ou  descontinuar temporariamente as funcionalidades, serviços e/ou conteúdos por  ela disponibilizados, a qualquer momento e a seu exclusivo critério, inclusive sempre que entender necessário para oferecer os melhores serviços,  conveniências e experiências para você.</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>A Zoox poderá, a qualquer tempo, alterar, adequar ou remodelar o conteúdo,  layout (disposição gráfica), funcionalidades e/ou ferramentas relacionadas a seus produtos e serviços, desde que esteja em conformidade com a legislação brasileira, em  especial a Lei nº 13.709 de 2018 (Lei Geral de Proteção de Dados) e a Lei  Federal nº 12.965 de 2014 (Marco Civil da Internet).</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>A Zoox pode, ainda, efetuar paralisações programadas para realizar a  manutenção, atualização e ajustes de configuração de seu produto, visando a  melhorias na qualidade dos serviços prestados a você, envidando seus melhores  esforços para que os horários de manutenção não coincidam com horários  comerciais nem de pico de acesso. No entanto, caso haja manutenção  emergencial a ser feita, ela poderá ocorrer dentro do horário comercial ou de  pico e sem aviso prévio, sendo que, nestes casos, a Zoox não será  responsabilizada pela indisponibilidade porque haverá uma forte justificativa  para que a manutenção ocorra dessa forma.</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>A Zoox não será responsável, sob quaisquer circunstâncias, por eventuais  perdas e danos, incluindo lucros cessantes, relacionados à suspensão do  acesso à Zoox. Você não possui qualquer direito para exigir a disponibilidade da  Zoox conforme melhor lhe convém, tampouco pode pleitear indenização ou  reparação de danos no caso de a Zoox permanecer fora do ar,  independentemente da motivação.</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>A Zoox poderá, a qualquer tempo, a seu exclusivo critério e sem qualquer  obrigação, indisponibilizar, temporariamente, determinadas funcionalidades ou  serviços até que eventuais inconformidades sejam readequadas, com o objetivo  de minimizar riscos de falhas humanas e/ou uso indevido dos produtos e serviços  da Zoox</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>A Zoox poderá, a seu exclusivo critério, restringir, limitar ou impedir, por qualquer meio ou forma, o seu acesso ao ecossistema da Zoox, especialmente nos casos repetidos de suspeitas de fraude ou quaisquer outras ações que prejudiquem ou  possam prejudicar o funcionamento de seus serviços e funcionalidades.</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>A Zoox reserva a si o direito de, a qualquer momento e sem aviso prévio,  suspender os serviços prestados e as funcionalidades disponíveis a você caso  você não cumpra qualquer das disposições previstas neste documento, ou  pratique, auxilie ou instigue atos que venham a prejudicar o bom funcionamento  do ecossistema da Zoox, ou venha a praticar atos ilícitos para, por exemplo, a  inserção de dados falsos e/ou incorretos, a utilização de cartões fraudulentos ou  inexistentes, dentre outros atos que possam infringir qualquer lei ou norma.</Text>

                    <Text maxFontSizeMultiplier={1.2} style={styles.titleTerms}>6. ISENÇÃO DE RESPONSABILIDADE PELA ZOOX</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>Cabe aos estabelecimentos hoteleiros a responsabilidade por atualizar as tarifas, disponibilidade de acomodação e outras informações publicadas em nossa  plataforma, sendo eles os únicos responsáveis por sua veracidade e precisão.</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>Da mesma forma, a Zoox não possui ou não pertence a nenhuma entidade  comercial explorada ou de propriedade dos estabelecimentos hoteleiros.</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>A Zoox não se responsabiliza por, ratifica ou endossa qualquer ato praticado pelo usuário na utilização da plataforma e nem quanto a quaisquer atos fraudulentos, omissões, falsa identidade ou quaisquer danos resultantes de acessos indevidos ou não autorizados em sua conta ocorridos por ação ou omissão por parte do  próprio usuário.</Text>

                    <Text maxFontSizeMultiplier={1.2} style={styles.titleTerms}>7. RESPONSABILIDADES DO USUÁRIO</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>Você se compromete a fornecer apenas informações legítimas, verídicas,  precisas, íntegras e idôneas, sob pena de ser responsabilizado civil e/ou  criminalmente. Além disso, a Zoox reserva a si o direito de recusar, suspender  ou até mesmo encerrar a sua conta caso você cometa qualquer infração contra  as cláusulas deste documento.</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>As informações pessoais que você nos fornecer serão atribuídas à FNRH (Ficha  Nacional de Registro de Hóspedes), que consiste em uma obrigação legal do  Hotel ou rede conveniada a manter, nos termos do Decreto nº 7.381, de 2 de  dezembro de 2010, que regulamenta a Lei do Turismo nº 11.771/2008.</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>Além disso, você se compromete a manter o sigilo e confidencialidade quanto às  suas informações de login e senha/PIN relativos à plataforma Zoox Pass,  cabendo a você contatar/notificar a Zoox imediatamente caso tenha  conhecimento de qualquer uso não autorizado de sua conta ou quaisquer outras  violações.</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>Você fica ciente de que será responsabilizado(a) pelos custos decorrentes da  reserva de hospedagem e demais obrigações por você contraídas nas  dependências do hotel ou rede conveniada.</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>A inexistência de contraprestação pecuniária quanto ao uso da plataforma não se vincula e nem se confunde com as obrigações onerosas as quais você contrair junto ao hotel ou rede  conveniada.</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>Você assume o compromisso de utilizar a plataforma Zoox Pass sob sua  responsabilidade, em acordo com a legislação vigente, boa-fé, melhores práticas e bons costumes, e em conformidade com os Termos de Uso e Política de Privacidade da plataforma, não devendo utilizar a solução da Zoox para fins  ilícitos, que atentem contra direitos de terceiros ou que infrinjam qualquer lei ou  norma aplicável.</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>Você se declara ciente de que não poderá acessar a conta de outra pessoa,  coletar dados pessoais de terceiros sem o conhecimento e consentimento deles,  nem realizar, sem autorização, o pré check-in na rede hoteleira em nome de  terceiros ou interferir no uso dos serviços por outros usuários. </Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>Em atendimento ao Decreto nº 7.381, de 2 de dezembro de 2010, que  regulamenta a Lei do Turismo nº 11.771/2008, em manter a FNRH, você se  declara ciente de que não poderá se abster a fornecer todos os dados solicitados  na plataforma para seu preenchimento, sob nenhum fundamento ou hipótese. A coleta de tais dados está amparada pela Lei nº 13.709/2018 (Lei Geral de  Proteção de Dados Pessoais), tendo em vista o cumprimento de obrigação legal  ou regulatória, a contratação do serviço por você e o seu consentimento.</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>Ao integrar o ecossistema da Zoox, você é responsável por e se compromete a:</Text>

                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>a. Utilizar corretamente e de forma ética o ecossistema da Zoox, respeitando  as condições que regulam a sua utilização e finalidade;</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>b. Fornecer informações e dados cadastrais corretos, completos e  atualizados, além de informar canal de contato eficiente e atualizado para  você ser contatado pela Zoox , caso necessário, sendo que você é  responsável civil e criminalmente por todas as informações que fornecer  à Zoox e se compromete a mantê-las atualizadas sempre que houver  alguma alteração;</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>c. Usar dispositivos e equipamentos compatíveis com os produtos da Zoox,  serviço de conexão à Internet com antivírus e firewall habilitados, e  sistemas operacionais / softwares devidamente atualizados;</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>d. Deixar seus sistemas de antispam, filtros similares ou configurações de  redirecionamento de mensagens ajustados de modo que não interfiram  no recebimento dos comunicados e materiais da Zoox, não sendo  aceitável nenhuma desculpa caso você não tenha tido acesso a algum e mail ou mensagem eletrônica enviada pela Zoox devido ao seu  descumprimento a estas orientações;</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>e. Respeitar todos os direitos de propriedade intelectual da Zoox, bem como  todos os direitos referentes a terceiros que porventura estejam ou  estiveram, de alguma forma, disponíveis na Zoox;</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>f. Não acessar as áreas de programação da Zoox, seu banco de dados ou  qualquer outro conjunto de informações que faça parte da atividade de  administração;</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>g. Não realizar ou permitir que se realize engenharia reversa, nem traduzir,  decompilar, copiar, modificar, reproduzir, alugar, sublicenciar, publicar,  divulgar, transmitir, emprestar, distribuir ou, de outra maneira, dispor das  ferramentas da Zoox, seus conteúdos e de suas funcionalidades;</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>h. Não utilizar softwares spider, ou de mineração de dados, de qualquer tipo  ou espécie, além de outro aqui não tipificado, mas que atue de modo  automatizado, tanto para realizar operações, massificadas ou não, de  coleta e processamento de dados para quaisquer outras finalidades não  expressamente autorizadas por este documento;</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>i. Não transmitir materiais contendo vírus de computador ou outros códigos,  arquivos, scripts, agentes ou programas de computador maliciosos, e</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>j. Não explorar, de forma maliciosa, a segurança da Zoox para a prática de  atos ilícitos, proibidos pela lei e por este documento, lesivos aos direitos  e interesses da Zoox e de terceiros, ou que, de qualquer forma, possa  danificar, inutilizar, sobrecarregar ou deteriorar o produto, os serviços,  funcionalidades e/ou o ecossistema da Zoox ou que de qualquer outra  forma possa prejudicá-la.</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>Você será responsabilizado, de forma exclusiva e integral, por qualquer dano  que causar à Zoox ou a terceiros em decorrência do não cumprimento das  obrigações aqui descritas ou da falsidade das informações prestadas.</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>As funcionalidades que compõem os produtos da Zoox são oferecidas na forma  de prestação de serviço e não geram a você nenhum direito sobre os softwares utilizados pela Zoox, seu conteúdo ou sobre as estruturas de informática que o  sustentam.</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>A eventual remoção, bloqueio ou suspensão de qualquer conteúdo ou  funcionalidade da Zoox em decorrência de alguma reclamação deverá ser  sempre compreendida como demonstração de intenção de evitar danos e  prejuízos com boa-fé e intenção de solução amigável de conflitos, jamais como  reconhecimento de culpa ou de qualquer infração pela Zoox a direito de terceiro.</Text>

                    <Text maxFontSizeMultiplier={1.2} style={styles.titleTerms}>8. POLÍTICA DE PRIVACIDADE</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>A Zoox está comprometida em respeitar e garantir a sua privacidade e a proteção  de seus dados pessoais, em conformidade com a Lei nº 13.709/2018 (Lei Geral  de Proteção de Dados Pessoais) e demais legislações aplicáveis.</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>Recomendamos que você leia nossa Política de Privacidade, que se incorpora  aos presentes Termos e Condições de Uso da plataforma Zoox Pass por  referência.</Text>

                    <Text maxFontSizeMultiplier={1.2} style={styles.titleTerms}>9. ENCARREGADO PELO TRATAMENTO DE DADOS PESSOAIS</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>A Zoox é Controladora e Operadora de dados responsável pelo tratamento de  suas informações pessoais e, conforme prevê a legislação, designamos um  Encarregado pela Proteção de Dados Pessoais para atuar como canal de  comunicação e garantia do pleno exercício de seus direitos como titular de dados  pessoais.</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>Você pode contatar nosso Encarregado pelo e-mail dpo@zooxsmart.com e  exercer todos os direitos que a legislação lhe garante.</Text>

                    <Text maxFontSizeMultiplier={1.2} style={styles.titleTerms}>10. RESTRIÇÕES DE IDADE</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>Nosso produto não é direcionado e nem é recomendado a menores de 18  (dezoito) anos, por se tratar de negociação de reservas a hotéis, o que requer a  maioridade legal para ser feita. Se você é responsável legal por algum menor de 18 (dezoito) anos e acredita  que ele nos enviou informações pessoais, entre em contato com o e-mail  dpo@zooxsmart.com para tratar a respeito desse assunto. Prontamente nos  disponibilizaremos a cuidar desses casos em total conformidade com a  legislação de proteção de dados e Estatuto da Criança e do Adolescente, visando sempre o melhor interesse do menor.</Text>

                    <Text maxFontSizeMultiplier={1.2} style={styles.titleTerms}>11. SERVIÇOS DE TERCEIROS</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>A Zoox reserva a si o direito de alterar, modificar, suspender, limitar ou  descontinuar partes de nosso serviço de check-in online de hotéis, incluindo  conteúdo licenciado por terceiros, sem prévio aviso ou responsabilidade.</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>A plataforma Zoox Pass poderá conter links que o direcionem a sites de terceiros , como anunciantes de produtos e serviços expostos na plataforma em  conformidade com a política de privacidade.</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>Alguns desses links permitem que você use e/ou seja apresentado a serviços e  produtos de acordo com a análise de seu perfil, conforme exposto e tratado na  Política de Privacidade, e de acordo com o seu consentimento. Não fazemos  nenhuma representação ou garantia em relação a esses serviços e produtos,  nem o fornecimento de acesso a esses serviços e produtos cria qualquer  responsabilidade à Zoox. Recomendamos que você leia atentamente os Termos  e Condições e a Política de Privacidade dos anunciantes e terceiros com quem  compartilhamos seus dados com o seu conhecimento e consentimento.</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>A Zoox tem o direito de anonimizar ou excluir todos os dados, arquivos ou outras  informações armazenadas em nossa base de dados relativas à conta do usuário  final, se os serviços utilizados por você forem encerrados, por qualquer motivo, especialmente os descritos neste documento. Ainda assim, a Zoox poderá ser obrigada a cumprir prazo de retenção de dados determinado pela legislação,  quando aplicável.</Text>

                    <Text maxFontSizeMultiplier={1.2} style={styles.titleTerms}>12. ATENDIMENTO E SUPORTE AO CLIENTE</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>O Atendimento ao cliente está disponível pelo email  suportezoox@zooxsmart.com ou pelo número 0800-326-0806 – por favor, atente  para o fato de que esse número pode não ser gratuito quando usado em alguns  telefones celulares. </Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>Nós empenharemos esforços razoáveis para fornecer acesso ininterrupto ao  serviço de check-in online. A Zoox, se possível e viável, executará a manutenção  de rotina fora do horário comercial. No entanto, podemos modificar ou suspender  temporariamente o serviço ou qualquer parte dele sem aviso prévio para reparo técnico de emergência.</Text>

                    <Text maxFontSizeMultiplier={1.2} style={styles.titleTerms}>13. PROPRIEDADE INTELECTUAL</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>Todos os direitos relativos à Zoox, bem como as suas funcionalidades, são de  titularidade da Zoox, incluindo, sem limitação, todos os direitos de propriedade  intelectual relacionados aos seus textos, imagens, gráficos, marcas, layouts,  códigos, bases de dados e demais conteúdos desenvolvidos direta ou  indiretamente pela Zoox (“Direitos de Propriedade Intelectual”). É  expressamente proibida a utilização, sem autorização prévia e expressa, de qualquer conteúdo ou marcas apresentadas pela Zoox. Você assume toda e  qualquer responsabilidade, de caráter civil e criminal, pela utilização indevida e  não autorizada dos Direitos de Propriedade Intelectual.</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>O uso comercial da expressão “Zoox” ou ainda de palavras que se assemelham  a esta, porém com grafia diferenciada, como marcas, nomes empresariais ou  nomes de domínio, além dos conteúdos das telas da Zoox, assim como os  programas de computador, bancos de dados, redes e seus arquivos, são de propriedade da Zoox e/ou estão protegidos pelas leis e tratados internacionais de  proteção à propriedade intelectual, incluindo as Leis Federais nº 9.609/98, nº  9.610/98, nº 9.279/96 e nº 10.406/2002.</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>Ao acessar o ecossistema da Zoox, você declara que irá respeitar todos os  direitos de propriedade intelectual da Zoox, incluindo, mas sem limitação, os  programas de computador, direitos autorais e direitos de propriedade industrial  sobre as marcas, patentes, nomes de domínio, denominação social e desenhos  industriais, depositados ou registrados em nome da Zoox, bem como de todos  os direitos referentes a terceiros que porventura estejam, ou estiveram, de  alguma forma, disponíveis na Zoox.</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>É proibida a utilização do ecossistema da Zoox, bem como a reprodução,  distribuição e divulgação, total ou parcial, dos textos, figuras e gráficos que a  compõem, para quaisquer finalidades que contrariem estes Termos e a Política  de Privacidade, sem prévia e expressa autorização da Zoox.</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>Caso você envie para a Zoox quaisquer ideias para novos produtos e serviços,  melhorias para os produtos e serviços já existentes ou campanhas, por exemplo,  você automaticamente autoriza que a Zoox aplique as novas ideias, ficando a  critério exclusivo da Zoox oferecer ou não qualquer tipo de recompensa  financeira ou compensação não financeira por suas ideias, sendo que você não  poderá reclamar nada nesse sentido.</Text>

                    <Text maxFontSizeMultiplier={1.2} style={styles.titleTerms}>14. ATUALIZAÇÃO DOS TERMOS E LEGISLAÇÃO APLICÁVEL</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>Os termos da Zoox poderão ser atualizados a qualquer tempo. Havendo  alterações substanciais, a Zoox se compromete a notificar você sobre a  atualização. </Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>Estes termos são regidos, interpretados e executados de acordo com a legislação brasileira, no idioma português, sendo eleito o foro do domicílio do  usuário para dirimir qualquer litígio ou controvérsia envolvendo o presente  documento.</Text>

                    <Text maxFontSizeMultiplier={1.2} style={styles.titleTerms}>POLÍTICA DE PRIVACIDADE ZOOX PASS - BR</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.subtitleTerms}>Atualizado em 19 de setembro de 2022.</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>Neste documento, você encontrará os seguintes tópicos:</Text>

                    <Text maxFontSizeMultiplier={1.2} style={styles.subtitleTerms}>1. INTRODUÇÃO DA POLÍTICA DE PRIVACIDADE</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>Você vai encontrar aqui algumas informações gerais sobre a importância de ler atentamente este documento e os Termos e Condições de uso para que você tenha um conhecimento claro e completo sobre como funciona o Zoox Pass em relação a você e possa decidir, com segurança, se deseja prosseguir com o cadastro e uso do Pass ou não.</Text>

                    <Text maxFontSizeMultiplier={1.2} style={styles.subtitleTerms}>2. QUAIS DADOS SERÃO COLETADOS</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>Esta seção é muito importante: nela, explicaremos quais são os dados pessoais coletados quando você se cadastra na Zoox e utiliza o Zoox Pass.</Text>

                    <Text maxFontSizeMultiplier={1.2} style={styles.subtitleTerms}>3. BASES LEGAIS QUE PERMITEM A COLETA E TRATAMENTO DE SEUS DADOS PELA ZOOX</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>Nesta seção, indicaremos as hipóteses legais que permitem a coleta e tratamento dos seus dados pessoais.</Text>

                    <Text maxFontSizeMultiplier={1.2} style={styles.subtitleTerms}>4. FINALIDADES DO TRATAMENTO DE DADOS</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>Você vai encontrar nesta seção informações sobre o que a Zoox e nossos clientes objetivam com o uso desses dados.</Text>

                    <Text maxFontSizeMultiplier={1.2} style={styles.subtitleTerms}>5. DURAÇÃO DO TRATAMENTO</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>Aqui, você poderá entender como funciona o tempo de duração do tratamento de seus dados pessoais.</Text>

                    <Text maxFontSizeMultiplier={1.2} style={styles.subtitleTerms}>6.  DO ESCANEAMENTO DE DOCUMENTOS</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>Nesta seção, explicaremos a necessidade de se ter alguns documentos escaneados por você em seu próprio dispositivo.</Text>

                    <Text maxFontSizeMultiplier={1.2} style={styles.subtitleTerms}>7.  TRATAMENTO DE DADOS SENSÍVEIS - DADO BIOMÉTRICO | RECONHECIMENTO FACIAL</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>Aqui, indicaremos as hipóteses que você poderá usufruir da funcionalidade de reconhecimento facial presente na plataforma Zoox Pass.</Text>

                    <Text maxFontSizeMultiplier={1.2} style={styles.subtitleTerms}>8. COMPARTILHAMENTO DE DADOS PESSOAIS</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>Nessa seção, explicamos como funciona o compartilhamento de dados dentro do Ecossistema da Zoox.</Text>

                    <Text maxFontSizeMultiplier={1.2} style={styles.subtitleTerms}>9. GERENCIAMENTO DE PRIVACIDADE E DIREITOS DO USUÁRIO</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>Neste tópico, você terá acesso a informações sobre quais são seus direitos garantidos por lei relacionados aos seus dados pessoais e como você pode exercê-los.</Text>

                    <Text maxFontSizeMultiplier={1.2} style={styles.subtitleTerms}>10. TRANSFERÊNCIA INTERNACIONAL DE DADOS</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>Aqui, você terá acesso a maiores informações sobre quando existe a possibilidade de armazenamento de seus dados fora do país de origem (onde ocorreu a coleta dos dados) e a medida que a Zoox adotou para minimizar a necessidade desse tipo de operação.</Text>

                    <Text maxFontSizeMultiplier={1.2} style={styles.subtitleTerms}>11. SEGURANÇA E PROTEÇÃO DE DADOS</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>Nesta seção, você encontrará informações gerais sobre como a Zoox aplica medidas de segurança para a proteção dos seus dados pessoais.</Text>

                    <Text maxFontSizeMultiplier={1.2} style={styles.subtitleTerms}>12. POLÍTICA DE QUALIFICAÇÃO DE DADOS</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>Esta seção se refere às informações que guardamos sobre você, seu perfil e comportamento de acordo com as suas respostas nas pesquisas que realizamos na plataforma.</Text>

                    <Text maxFontSizeMultiplier={1.2} style={styles.subtitleTerms}>13. ATUALIZAÇÃO DA POLÍTICA</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>Esta seção informa sobre a possibilidade da Zoox alterar e atualizar, a qualquer momento, as disposições dos seus documentos, como esta Política de Privacidade e os Termos e Condições de Uso do Pass. Recomendamos fortemente que você sempre os leia, a cada novo acesso ao Zoox Pass.</Text>

                    <Text maxFontSizeMultiplier={1.2} style={styles.titleTerms}>1. INTRODUÇÃO DA POLÍTICA DE PRIVACIDADE</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>Esta Política de Privacidade objetiva contemplar informações a respeito do modo como tratamos total ou parcialmente, de forma automatizada ou não os seus dados pessoais como usuário da plataforma de serviços de check-in online Zoox Pass.</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>A Zoox recomenda a você ler atentamente esta Política de Privacidade e os Termos e Condições de Uso em apartado, os quais devem ser interpretados conjuntamente, antes de efetuar o cadastro em nossa solução para, frente as informações que temos a lhe apresentar quanto aos aspectos das operações de tratamento que realizaremos com seus dados, você avaliar se estão em conformidade com as suas perspectivas e após sua clara compreensão, preencher o seu cadastro em nossa plataforma e utilizá-la. Ressaltamos que o uso da nossa plataforma não resulta na sua obrigação de efetuar qualquer contraprestação pecuniária à Zoox.</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>Esclarecemos a você que realizamos nossas atividades de tratamento de dados em conformidade com a Lei nº 13.709/2018 (Lei Geral de Proteção de Dados), Lei nº 12.965/2014 (Lei do Marco Civil da Internet), Lei nº 8.078/1990 (Código de Defesa do Consumidor) e com as demais legislações que se façam pertinentes a assegurar e garantir seus direitos, em especial, a sua privacidade! Recomendamos gentilmente que, caso não se identifique com os nossos regulamentos, não realize seu cadastro e se abstenha em fazer uso da plataforma de check-in online Zoox Pass.</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>Ressaltamos, ainda, caso já seja usuário do nosso produto, que garantimos a você o direito de sair da nossa base de dados a QUALQUER MOMENTO! No entanto, sinalizamos que isso afetará diretamente a praticidade e facilidade que você tem em utilizar nossos serviços de check-in online em todos os locais do Brasil em que disponibilizamos nosso produto</Text>

                    <Text maxFontSizeMultiplier={1.2} style={styles.titleTerms}>2. QUAIS DADOS SERÃO COLETADOS</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>● Dados cadastrais do usuário – Ficha Nacional de Registro de Hóspedes: Para darmos cumprimento a fins legais, coletamos todos os dados que a legislação do turismo exige que sejam preenchidos na FNRH (Ficha Nacional de Registro de Hóspedes).</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>● Dados financeiros: Para intermediarmos as operações financeiras a serem feitas com seus dados, solicitamos a coleta destes para este fim. Lembrando que, conforme exposto nos Termos e Condições de Uso, nem a Zoox ou hotel armazenarão os seus dados. Isto será feito pela Mundipagg, visando garantir a você, maior excelência quanto à segurança dos seus dados.</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>● Dados informados no e-mail de contato com o Encarregado de Proteção de Dados e/ou fornecidos ao contatar o suporte ao usuário: Quando você realiza solicitações ao nosso Encarregado de Proteção de Dados para obtenção de informações ou exercício de direitos e/ou ao suporte do usuário para resolução de problemas técnicos, por exemplo, trataremos os dados que você nos fornece para resposta e cumprimento das suas solicitações, reclamações e direitos.</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>● Registros de acesso do usuário: Em atendimento às disposições do art. 15 caput e parágrafos da Lei 12.965/2014 (Lei do Marco Civil da Internet), os seus registros de acesso coletados serão armazenados por pelo menos 06 (seis) meses ou por prazo maior se decisão judicial assim dispuser.</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>● Dados fornecidos através de respostas às pesquisas na plataforma: Ao fazer uso da plataforma Zoox Pass, poderão surgir a você algumas perguntas de pesquisas que os clientes desejam saber sobre você para melhor entender o seu perfil, comportamento e preferências e, desta forma, promover-lhe experiências e vendas mais aprimoradas. Você não será obrigado(a) a responder as pesquisas e pode se abster em fazê-lo, não sendo isso fator condicionante para fazer uso do nosso produto. Apenas responda caso se sinta confortável para isso! As perguntas são variadas e sua natureza depende do que cada cliente visa adquirir de conhecimento sobre você.</Text>

                    <Text maxFontSizeMultiplier={1.2} style={styles.titleTerms}>3. BASES LEGAIS QUE PERMITEM A COLETA E TRATAMENTO DE SEUS DADOS PELA ZOOX</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>A coleta e tratamento (qualquer operação com seus dados pessoais, como armazenamento e uso) são autorizados com base em 5 (cinco) hipóteses previstas na lei: (i) execução de contrato em que o usuário é parte (ou seja, você é quem inicia o processo de contratação do Zoox Pass, aceitando os Termos de Uso e Política de Privacidade, inserindo seus dados para o cadastro e prosseguindo com o serviço de check-in online Zoox Pass), (ii) cumprimento de obrigação imposta por lei para a Zoox (em coletar e guardar todos os dados que a legislação do turismo exige que sejam preenchidos na FNRH - Ficha Nacional de Registro de Hóspedes, bem como registrar e guardar os registros de conexão por pelo menos seis meses para cumprir o que regula o Marco Civil da Internet); (iii) legítimo interesse da Zoox e do estabelecimento cliente da Zoox em fornecer o serviço de check-in online para você; (iv) consentimento e (v) prevenção à fraude e à segurança do titular, sendo as bases legais descritas nos itens (iv) e (v) utilizadas para coleta de dados biométricos nos processos de identificação e autenticação.</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>Para uso da plataforma do Zoox Pass, requisitamos o seu aceite, que nada mais é do que  uma autorização fornecida por você no momento em que preenche a caixinha de marcação na página inicial da plataforma Zoox Pass, a qual chamamos de “opt-in” que significa “permissão”, que obrigatoriamente estará vazia de modo a não influenciar a sua vontade.</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>Lembramos a você a importância de realizar a leitura desta Política e de nossos Termos e Condições de Uso ANTES de nos conceder o seu aceite e de nos fornecer as suas informações pessoais. Pretendemos coletar a sua autorização em conformidade com o que a legislação em vigor dispõe, ou seja, com vistas aos princípios legais, é imprescindível que seu aceite seja fornecido de forma livre, informada com base na transparência e nas informações que disponibilizamos a você e inequívoca, ou seja, que não lhe gere qualquer dúvida ou erro no ato de autorizar.</Text>

                    <Text maxFontSizeMultiplier={1.2} style={styles.titleTerms}>4. FINALIDADES DO TRATAMENTO DE DADOS</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>Para nós, é muito importante deixarmos claro a você quais são as finalidades com as quais nos propomos em operar tratamento com os seus dados.</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>Nosso propósito é coletar, armazenar e operar outras atividades de tratamento com os seus dados para intermediarmos suas reservas a hotéis, bem como propiciarmos em um ambiente digitalizado que você auto gerencie a sua estadia, desde a reserva do hotel e pré check-in, como a realização de pedidos ao hotel, pagamento da estadia, emissão da chave do quarto, check-out, dentre outros serviços que tornarão a sua passagem pelo hotel mais facilitada, aprimorada e assim, mais satisfatória.</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>Para que ocorra a plena satisfação de todo esse fluxo descrito, será necessário compartilharmos os seus dados com o hotel ou rede conveniada por você escolhido. A partir da coleta de suas informações, com sua autorização para qualificação de dados, visamos lhe atribuir outras facilidades quanto a todo fluxo de nossos produtos, como, por exemplo, a partir da coleta feita através do Zoox Pass, nós facilitamos a sua conexão ao Zoox Wi-fi nos diversos pontos em que estamos localizados em âmbito nacional e estrangeiro, sem que você tenha que passar pela fase de cadastro na plataforma.</Text>

                    <Text maxFontSizeMultiplier={1.2} style={styles.titleTerms}>5. DURAÇÃO DO TRATAMENTO DOS DADOS</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>Realizaremos operações de tratamento com seus dados de forma contínua enquanto você estiver cadastrado como usuário da plataforma Zoox Pass e, caso venha solicitar o cancelamento do cadastro, somente persistiremos com o tratamento caso haja fundada necessidade e esta se enquadre em uma das hipóteses previstas em lei ou quando o tratamento puder ser justificado com base em outras bases legais ou coleta, por meio de algum de nossos outros produtos.</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>Entendemos que não podemos estabelecer prazo determinado de duração do tratamento a ser realizado com os seus dados, tendo em vista garantirmos a você a possibilidade e praticidade de fazer uso contínuo dos serviços descritos nesta Política de Privacidade a qualquer tempo e em qualquer local do Brasil em que estivermos por intermédio dos nossos clientes.</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>Prezamos pela sua satisfação e sucesso como usuário do nosso produto e seria incabível se contra a sua vontade nós indisponibilizássemos nosso produto e eliminássemos os seus dados, impedindo-o de usufruir da nossa solução ou ter que realizar um novo cadastro sem que você tenha solicitado. Além disso, comprometendo a disponibilidade dos seus dados dessa forma, estaríamos afetando um dos pilares que embasam a segurança da informação.</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>Portanto, nos contate a qualquer tempo para exercer quaisquer dos direitos que a legislação lhe garante, em especial, o direito de revogar o seu consentimento total ou parcialmente ou até mesmo de solicitar a eliminação dos seus dados pessoais.</Text>

                    <Text maxFontSizeMultiplier={1.2} style={styles.titleTerms}>6. DO ESCANEAMENTO DE DOCUMENTOS</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>Através da nossa solução Zoox Pass, você precisará escanear em seu próprio dispositivo, imagens de alguns de seus documentos para que possamos encaminhar essas imagens ao hotel ou rede conveniada por você escolhido. Não se preocupe, nós da Zoox não manteremos essas imagens armazenadas em nossa base de dados, mas tão somente encaminharemos ao hotel para que eles possam gerir esses documentos de acordo com as exigências legais que lhes são feitas e para fins de verificação de identidade, visando coibir quaisquer atos fraudulentos por terceiros que possam gerar danos a você.</Text>

                    <Text maxFontSizeMultiplier={1.2} style={styles.titleTerms}>7. TRATAMENTO DE DADOS SENSÍVEIS - DADO BIOMÉTRICO | RECONHECIMENTO FACIAL</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>Nossa plataforma possibilita a você usufruir da funcionalidade de reconhecimento facial para autenticar e validar as suas operações no autogerenciamento de sua estadia. A partir da foto que você mesmo captura do seu celular em nossa plataforma, você não ficará restrito a sempre se autenticar através de senhas, mas sim através da inteligência que a tecnologia atribui ao reconhecimento individualizado da sua face. Como dado sensível, por ser biométrico, nos comprometemos em operar os seus dados em consonância com o que a Lei Geral de Proteção de Dados dispõe. Utilizamos duas bases legais para justificar o tratamento, sendo certo que a coleta de seus dados biométricos só ocorrerá mediante o seu consentimento expresso. Nosso objetivo é gerar satisfação, conveniência, praticidade e celeridade a sua vida e operações rotineiras. Para isso, nos preocupamos com os direitos que a legislação lhe confere quanto à privacidade, proteção da liberdade, honra, vida privada e dados, tendo em vista a grande importância que este dado biométrico tem para você, por ser único, não modificável e por representar você.</Text>

                    <Text maxFontSizeMultiplier={1.2} style={styles.titleTerms}>8. COMPARTILHAMENTO DE DADOS PESSOAIS</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>É importante ressaltar que os seus dados cadastrais coletados via Zoox Pass integrarão a nossa base de dados e poderão ser utilizados na prestação de serviços para outros clientes da Zoox, aqueles que contratam nossa solução de inteligência de dados e que não estão diretamente ligados à relação criada para fins da prestação de serviços do produto a que se refere esta Política de Privacidade.</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>A utilização de seus dados nos termos indicados no parágrafo acima dependerá da obtenção pelo cliente, aquele que vai utilizar a solução de inteligência de dados da Zoox, de autorização na forma da lei para o tratamento pretendido pelos meios empregados na relação mantida entre você e esse cliente, sem necessariamente envolver a Zoox. Ou seja, você deverá ser informado e deverá haver base legal para o tratamento específico pretendido por esse cliente. Caberá ao cliente da Zoox informar diretamente sobre a finalidade e as oportunidades de negócios, vantagens ou benefícios que deverão resultar de tal tratamento. Seus dados pessoais só serão utilizados nestes casos quando nossos clientes confirmarem que obtiveram as autorizações pertinentes em seus respectivos ambientes, adicionalmente à autorização obtida nos termos desta Política de Privacidade. Além disso, a Zoox esclarece que, nesse contexto, o tratamento de dados a ser realizado será definido pelo cliente, aquele que contrata a solução de inteligência de dados da Zoox, conforme as informações disponibilizadas a você e observados os termos da legislação aplicável.</Text>

                    <Text maxFontSizeMultiplier={1.2} style={styles.titleTerms}>9. GERENCIAMENTO DE PRIVACIDADE E DIREITOS DO USUÁRIO</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>É nosso dever e assumimos o compromisso de assegurar o atendimento dos seus direitos como usuário do nosso produto. A Lei Geral de Proteção de Dados elenca um rol de direitos exercíveis pelos titulares dos dados e nós da Zoox garantimos a você a possibilidade de exercê-los a qualquer tempo, entrando em contato com nosso Encarregado de Proteção de Dados, através do e-mail: dpo@zooxsmart.com informando no campo do assunto “Proteção de dados”. Ao nos contatar, visando garantir o cumprimento da sua solicitação, pedimos a você que:</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>- Caso já seja usuário do nosso produto, se identifique brevemente fornecendo no corpo do e-mail os seguintes dados: nome completo; data de nascimento; CPF e e-mail cadastrado na plataforma;</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>- Especifique o direito que visa exercer;</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>- Caso ainda não faça parte do nosso ecossistema de dados e somente busque informações e esclarecimentos, não será necessário fornecer qualquer identificação. Nesta hipótese, responderemos à sua solicitação e asseguramos que não iremos realizar qualquer outra operação de tratamento com o seu endereço de e-mail.</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>Responderemos às suas solicitações em prazo razoável nas situações em que a Lei não dispuser de prazo específico. Além disso, o Encarregado de Proteção de Dados será o responsável por ter acesso e atender às suas solicitações. No entanto, ressaltamos que, a depender da natureza de sua solicitação, poderão outros Encarregados de Proteção de Dados de empresas com as quais compartilhamos os seus dados, com sua autorização, tomar ciência do teor da sua requisição e tomar providências conjuntas que se façam necessárias. Mas não se preocupe, em resposta à sua solicitação, informaremos tal fato caso se aplique ao seu caso.</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>Através deste e-mail, você poderá:</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>1. Solicitar informações sobre o tratamento que realizamos com seus dados de forma simplificada ou detalhada, bem como obter informações sobre a possibilidade de não fornecer consentimento e quais as consequências desta negativa;</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>2. Acessar e corrigir as suas informações;</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>3. Solicitar portabilidade, anonimização, limitação, oposição, bloqueio ou eliminação total ou parcial dos seus dados;</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>4. Solicitar informações sobre compartilhamento dos dados fornecidos com entes públicos e/ou privados e,</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>5. Requerer revogação do seu consentimento a qualquer momento.</Text>

                    <Text maxFontSizeMultiplier={1.2} style={styles.titleTerms}>10.TRANSFERÊNCIA INTERNACIONAL DE DADOS</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>Para melhor garantir segurança no armazenamento dos seus dados pessoais, armazenamos nossa base de dados na AWS (Amazon Web Services) e nosso data center fica localizado no Norte da Virgínia, nos Estados Unidos. Em decorrência disso, informamos que realizamos a transferência internacional de dados, mas que o fazemos de acordo com a legislação brasileira e também pautada na legislação americana de proteção de dados dos consumidores da Califórnia (CCPA), visando assegurar a máxima privacidade dos nossos usuários.</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>Entretanto, alguns dos nossos clientes optam pelo armazenamento de dados em território brasileiro e o fazemos alocando nossa base de dados no estado de São Paulo/BR.</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>Somente realizaremos transferência internacional de dados para países e agentes que aplicam as melhores práticas internacionais de proteção de dados pessoais e que possuam níveis de proteção e privacidade adequados para melhor garantir a segurança das suas informações.</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>Ressaltamos que, caso você não consinta com a transferência internacional das suas informações pessoais, você deve se abster de utilizar nosso produto por, desta forma, tornar inviável algumas atividades de tratamento internacionais.</Text>

                    <Text maxFontSizeMultiplier={1.2} style={styles.titleTerms}>11.SEGURANÇA E PROTEÇÃO DE DADOS</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>Assumimos o compromisso de aplicar medidas técnicas e organizacionais aptas a proteger as suas informações pessoais de acessos não autorizados, destruição, perda, alteração, comunicação, difusão indevida e exfiltração. Nos comprometemos, ainda, a comunicar a você em prazo razoável, caso ocorra qualquer incidente de segurança que viole ou possa violar a sua privacidade, proteção e liberdade. Embasamos nossas atividades nos conceitos e princípios da segurança da informação. Desta forma, prezamos por garantir a confidencialidade, disponibilidade e integridade dos seus dados pessoais.</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>Como forma adicional de aplicar um alto padrão de segurança no armazenamento e tratamento de seus dados, a Zoox utiliza a nuvem da Amazon (também conhecida pela sigla “AWS”), que aplica as técnicas mais avançadas de proteção de dados e segue as melhores práticas internacionais de segurança da informação, sendo certificada e recertificada no atendimento a todos os requisitos de segurança determinados pela ISO 27017 (código de melhores práticas internacionais para segurança da informação em nuvem) e ISO 27018 (código de melhores práticas internacionais para proteção de dados pessoais em nuvem). Maiores informações sobre essas certificações bem como a cópia do certificado encontram-se disponíveis em: https://aws.amazon.com/pt/compliance/iso-27017-faqs/ e https://aws.amazon.com/compliance/iso-27018-faqs/.</Text>

                    <Text maxFontSizeMultiplier={1.2} style={styles.titleTerms}>12.POLÍTICA DE QUALIFICAÇÃO DE DADOS</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>Em acordo com a sua vontade, quanto mais nós da Zoox e nossos clientes sabemos sobre você, mais podemos lhe promover conveniência e melhores experiências, direcionando a você nossas melhores ofertas de produtos e serviços. A qualificação de dados de que trata esta seção se refere à coleção de informações que guardamos sobre você, seu perfil e comportamento de acordo com as suas respostas nas pesquisas que realizamos na plataforma. Somente iremos qualificar dados de acordo com a sua autorização, de forma adequada, transparente e mínima, ou seja, não solicitaremos informações que desviem as finalidades pretendidas e informadas e ressaltamos que isso não afetará a usabilidade da plataforma caso você não queira fornecer suas informações.</Text>

                    <Text maxFontSizeMultiplier={1.2} style={styles.titleTerms}>13. ATUALIZAÇÃO DA POLÍTICA</Text>
                    <Text maxFontSizeMultiplier={1.2} style={styles.text}>A Política de Privacidade da Zoox poderá ser atualizada a qualquer tempo, sempre que houver alteração no produto e/ou na legislação que impacte o uso do Zoox Pass. Esta Política é regida, interpretada e executada de acordo com a legislação aplicável no local de fornecimento da plataforma do Zoox Pass e incidente sobre a operação da Zoox.</Text>
                </View>

                <View style={styles.terms}>
                    <TouchableOpacity
                        style={[styles.buttonTerms, terms && { borderColor: "#E06E78" }]}
                        onPress={() => setTerms(!terms)}
                    >
                        <View
                            style={terms && styles.acceptTerms}
                        ></View>
                    </TouchableOpacity>

                    <Text style={styles.termsText}>Li e concordo com os Termos de Uso</Text>
                </View>

                <TouchableOpacity
                    onPress={() => {
                        terms && 
                        navigation.navigate("CheckIn", {localName, localAddress, listProducts});
                        setTermsCheckIn(true);
                    }}
                    style={terms ? styles.nextButtonActive : styles.nextButtonDisabled}
                >
                    <Text style={styles.nextButtonText}>Avançar</Text>
                </TouchableOpacity>
            </ScrollView>
        </View>
    )
}
